#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           4
bspc config split_ratio          0.50

bspc rule -a Firefox desktop=I state=fullscreen
bspc rule -a discord desktop=II state=fullscreen
bspc rule -a Code desktop=III state=fullscreen
bash ~/.config/bspwm/launch_stuff.sh &
